### ISSUE TITLE
I download and run it but nothing show

### ISSUE THREAD

**Issue by hackerlor84** [UnknownWebPT/Bizfum-Stealer#1]
I download and run it but nothing show

**Comment by UnknownWebPT** [comment]
Could you provide more information? These things would help to identify the issue:

1. **What OS are you on?**
_If not Windows, the build.sh automatic building hasn't been tested yet. The program is being developed on Windows, meaning the main priority is the build.bat file and the main stealer code._

2. **What are you using to compile?**
_If not Mingw64 gcc, compiling hasn't been tested on other platforms such as Cygwin. Someday I will do more testing on those, but as I mentioned, it's not the main priority at the moment._

3. **What output did you get?**
_Your comment lacks detailed information, making it hard to determine what is wrong. Please share more information about the kind of output you received. Were there any errors or output during either compilation or execution?_

Thanks for reporting! : )
